pool:
  name: Hosted Ubuntu 1604

variables:
  buildNumber: '10.0.0.1000'

steps:
- powershell: |
   Write-Host "Generating Build Number"
   $baseDate = [datetime]"01/01/2000"
   $currentDate = $(Get-Date).ToUniversalTime()
   $interval = NEW-TIMESPAN –Start $baseDate –End $currentDate
   $days = $interval.Days
   Write-Host "##vso[task.setvariable variable=buildNumber]10.0.$days"
  displayName: 'PowerShell Script'

- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: '$(Parameters.RestoreBuildProjects)'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: '$(Parameters.RestoreBuildProjects)'
    arguments: '--configuration $(BuildConfiguration) -p:Version=$(buildNumber).$(Build.BuildId)'

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    projects: '$(Parameters.TestProjects)'
    arguments: '--configuration $(BuildConfiguration)'
  enabled: false

- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory) -p:Version=$(buildNumber).$(Build.BuildId)'
    zipAfterPublish: True

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
