steps:
- task: AzureRmWebAppDeployment@4
  displayName: 'Deploy Azure App Service'
  inputs:
    azureSubscription: '$(Parameters.ConnectedServiceName)'
    appType: '$(Parameters.WebAppKind)'
    WebAppName: '$(Parameters.WebAppName)'
    deployToSlotOrASE: true
    ResourceGroupName: 'moonglade-rsg'
    SlotName: staging
    enableCustomDeployment: true
    RemoveAdditionalFilesFlag: true
    ExcludeFilesFromAppDataFlag: false